fix(JOHNZON-397): protection against very slow BigDecimal to BigInteger conversion at large scale
apache/incubator-johnzon pull request #105
Opened 2023-05-10 21:20 UTC by jeanouii

Requires maybe an option to configure the limit. Not sure if anyone needs something bigger than 1k digits.

2023-05-11 06:34 UTC, rmannibucau requested changes
Ok with a toggle + test for the error case to me

2023-05-11 06:34 UTC, rmannibucau commented on johnzon-core/src/main/java/org/apache/johnzon/core/JsonNumberImpl.java
> +    private void checkBigIntegerScale() {
guess we need a toggle in the `Map` + `JsonbConfig` + `MapperBuilder` to disable it for backward compat - it stays legal?

2023-05-11 06:34 UTC, rmannibucau commented on johnzon-core/src/test/java/org/apache/johnzon/core/JsonNumberTest.java
> +    public void testSlowBigIntegerConversion() {
maybe test failing cases?

2023-05-11 08:40 UTC, jeanouii commented on johnzon-core/src/test/java/org/apache/johnzon/core/JsonNumberTest.java
> +    public void testSlowBigIntegerConversion() {
It's right bellow

2023-05-16 10:48 UTC, jgallimore approved these changes

2023-05-16 12:36 UTC, merged